# Generated by Django 4.0.6 on 2022-07-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
