# Generated by Django 4.0.6 on 2022-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_newsletterusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterusers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
